default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>
  timeout: 5000

development:
  <<: *default
  database: bilinho
test:
  <<: *default
  database: bilinho

production:
  <<: *default
  database: bilinho